# ssh into the instance and backup to s3 bucket
#
#
name: backup

on:
  push:
    branches:
      - 16-backup-strategy

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - name: start docker compose 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }} 
        username: root
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker cp wp1:/var/www/html/wp-content .
          docker exec ${{ secrets.WORDPRESS_DB_HOST }} mariadb-dump -u ${{ secrets.WORDPRESS_DB_USER }} -p${{ secrets.WORDPRESS_DB_PASSWORD }} ${{ secrets.WORDPRESS_DB_NAME }} > backup.sql
          
          docker run --rm -it amazon/aws-cli s3 cp test.sql s3://${{ secrets.S3_BUCKET_NAME }}/test.sql
          docker run --rm -it amazon/aws-cli aws s3 cp wp-content s3://${{ secrets.S3_BUCKET_NAME }}/wp-content --recursive
