# ssh into the instance and backup to s3 bucket
#
#
name: backup

on:
  push:
    branches:
      - 16-backup-strategy

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - name: start docker compose 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }} 
        username: root
        key: ${{ secrets.SSH_KEY }}
        script: |
          pwd 
          ls
          docker cp wp1:/var/www/html/wp-content .
          docker exec ${{ secrets.WORDPRESS_DB_HOST }} mariadb-dump -u ${{ secrets.WORDPRESS_DB_USER }} -p${{ secrets.WORDPRESS_DB_PASSWORD }} ${{ secrets.WORDPRESS_DB_NAME }} > backup.sql
          source app/.env
          echo $BACKUP_BUCKET_NAME

          pwd
          ls 

          docker run --rm \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -v $(pwd):/backup amazon/aws-cli s3 cp /backup/backup.sql s3://$BACKUP_BUCKET_NAME/backup.sql
          docker run --rm \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -v $(pwd):/backup amazon/aws-cli s3 cp /backup/wp-content s3://$BACKUP_BUCKET_NAME/wp-content
