name: Deploy

on:
  push:
    branches:
      - 7-deploy-docker-compose-setup

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: rsync deployments
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -Pav 
        path: app/ 
        remote_path: /root
        remote_host: ${{ secrets.SERVER_IP }} 
        remote_user: root
        remote_key: ${{ secrets.SSH_KEY }}
    - name: ssh test 
      run: |
        ssh -v -i ${{ secrets.SSH_KEY }} root@${{ secrets.SERVER_IP }} << 'EOF'
          pwd
          ls -al
          sudo docker compose up -d --no-deps --build --remove-orphans
        EOF
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
    - name: ssh to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }} 
        username: root
        key: ${{ secrets.SSH_KEY }}
        script: |
          pwd
          ls -al
          sudo docker compose up -d --no-deps --build --remove-orphans
