name: Provision Meta

on:
  push:
    branches:
      - main 
    paths:
      - 'infra/meta/**'

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      working-directory: ./infra/meta
      run: npm install

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1 
    - name: Set up Pulumi
      id: pulumi
      uses: pulumi/actions@v5
      with:
        stack-name: prod
        work-dir: ./infra/meta
        command:  up
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

    - name: Get Bucket Name from Pulumi Output
      id: pulumi_output
      working-directory: ./infra/meta
      run: |
         echo "BACKUP_BUCKET_NAME=$(pulumi stack output backupBucketName --stack prod)" >> $GITHUB_OUTPUT
    - name: echo output
      run: echo ${{ steps.pulumi_output.outputs.BACKUP_BUCKET_NAME }}

    - name: Store Backup Bucket Name
      run: gh secret set BACKUP_BUCKET_NAME --body "$BACKUP_BUCKET_NAME" 
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        BACKUP_BUCKET_NAME: ${{ steps.pulumi_output.outputs.BACKUP_BUCKET_NAME }}
