name: seed wordpress

on:
  push:
    branches:
      - 9-seed-wordpress-data 
  

jobs:
  seed: 
    runs-on: ubuntu-latest
    steps:
    - name: pull backup and seed 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }} 
        username: root
        key: ${{ secrets.SSH_KEY }}
        script: |
          source app/.env
          mkdir restore
          docker run --rm \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -v $(pwd)/restore:/restore amazon/aws-cli \
            s3 cp s3://$BACKUP_BUCKET_NAME/backup.sql /restore
          docker run --rm \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -v $(pwd)/restore:/restore amazon/aws-cli \
            s3 sync s3://$BACKUP_BUCKET_NAME/wp-content /restore/wp-content

          pwd 
          ls
          ls restore
          #docker cp wp-content wp1:/var/www/html/
          #docker exec ${{ secrets.WORDPRESS_DB_HOST }} mariadb -u ${{ secrets.WORDPRESS_DB_USER }} -p${{ secrets.WORDPRESS_DB_PASSWORD }} ${{ secrets.WORDPRESS_DB_NAME }} < backup.sql



